[package]
name = "leptos-bulma"
description = "A Leptos component library based on Bulma CSS framework."
version = "0.0.0-alpha.4"
edition = "2021"
authors = ["Javier E. <jaedns@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/javierEd/leptos-bulma.git"
categories = ["gui"]
keywords = ["components", "leptos", "ui", "web"]
exclude = [
    ".editorconfig",
    "bulma.jpg",
    "CHANGELOG.md",
    "docs",
    "leptosfmt.toml",
]

[dependencies]
grass = { version = "0.13", default-features = false }
leptos = "0.6"
leptos_router = "0.6"
leptos-use = "0.10"

[features]
ssr = ["leptos-use/ssr"]
