[package]
name = "leptos-bulma"
description = "A Leptos component library based on Bulma CSS framework."
version = "0.0.0-alpha.3"
edition = "2021"
authors = ["Javier E. <jaedns@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/javierEd/leptos-bulma.git"
categories = ["gui"]
keywords = ["components", "leptos", "ui", "web"]
exclude = [
    ".editorconfig",
    "bulma.jpg",
    "CHANGELOG.md",
    "docs",
    "leptosfmt.toml",
]

[dependencies]
leptos = "0.5"
leptos-use = "0.9"
